# Builds the jar and uploads it as an artifact
name: Build commit
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - run: commit=${'${{ github.sha }}':0:8}
      - name: Build with Maven
        run: mvn -B package --file pom.xml -Drevision=${{ github.ref_name }}-$commit
      - name: Copy artifacts
        run: mkdir staging && cp target/FunkyMachines-*.jar staging
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: FunkyMachines-${{ github.ref_name }}-$commit
          path: staging
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: HYoBPYWG
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-files: staging/FunkyMachines-*.jar
          modrinth-name: ${{ github.ref_name }}-$commit
          version: ${{ github.ref_name }}-$commit
          version-type: alpha
          game-versions: ">=1.20"
          loaders: |
            paper
            purpur
